<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQJgl5g3\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQJgl5g3/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQJgl5g3.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQJgl5g3\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQJgl5g3\appAppKernelProdContainer([
    'container.build_hash' => 'QJgl5g3',
    'container.build_id' => 'a93cacad',
    'container.build_time' => 1740125406,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQJgl5g3');
