<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container760BEXR\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container760BEXR/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container760BEXR.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container760BEXR\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container760BEXR\appAppKernelProdContainer([
    'container.build_hash' => '760BEXR',
    'container.build_id' => '82dc66c0',
    'container.build_time' => 1739886839,
], __DIR__.\DIRECTORY_SEPARATOR.'Container760BEXR');
