<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyMSE73Pg/NrCgnPtX1NJ'."\n".'CQwGi54/pUrx9npf5QLXc6OwAGRClWJePfaL1d55B8F1JhPbjVbf5T4xyMZ2zvUz'."\n".'1zgbYuu58ZfvTvQafYnGKovTiv8w2vULG3T42wfW+vnyXEdlMLmIZY5difqu0ynn'."\n".'k9Ig0xb8MkJMoF74iZ7tnoQAdrcacajtCi1r2Skn6oT7m+grtsDswjjLLfV2GY3m'."\n".'40wmFN1RQHN1rvIDSbskDM+3nZrKya0sTdlSXPyR0WGL0dBuHgeb+BZf2d/gF3TB'."\n".'m0YFTbUW5CiymZNZVGGzQ24aeM4nTTsL0KQ/Y0Fvod/OeWdzhHn1lHOdgWSwoW4G'."\n".'twIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
