<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP3dobR9\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP3dobR9/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP3dobR9.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP3dobR9\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerP3dobR9\appAppKernelDevDebugContainer([
    'container.build_hash' => 'P3dobR9',
    'container.build_id' => '81206dab',
    'container.build_time' => 1739957094,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP3dobR9');
